export const IPC = {
  bootstrapGet: 'bootstrap:get',
  workspaceChoose: 'workspace:choose',
  workspaceOpen: 'workspace:open',
  fileOpen: 'file:open',
  recentFiles: 'file:recent',
  recentFileOpen: 'file:open-recent',
  fileSave: 'file:save',
  runStart: 'run:start',
  runStop: 'run:stop',
  runForceStop: 'run:force-stop',
  runOutput: 'run:output',
  runExit: 'run:exit',
  previewStart: 'preview:start',
  previewStop: 'preview:stop',
  previewBounds: 'preview:bounds',
  previewOutput: 'preview:output',
  previewState: 'preview:state',
  previewMessage: 'preview:message',
  packagesList: 'packages:list',
  packagesTypes: 'packages:types',
  packagesInstall: 'packages:install',
  packagesSync: 'packages:sync',
  packagesUninstall: 'packages:uninstall',
  packagesStop: 'packages:stop',
  packagesOutput: 'packages:output',
  appCommand: 'app:command'
} as const
